# Generated by Django 3.1.7 on 2021-04-01 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('input', '0002_auto_20210302_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund',
            options={'ordering': ['item_id']},
        ),
        migrations.AlterField(
            model_name='clothing',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='input.item'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='input.clothingtype'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='input.donor'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='food',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='input.item'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='input.item'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='input.fundtype'),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='business_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='input.business'),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='input.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='input.donation'),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='input.item'),
        ),
    ]
