# Generated by Django 3.1.7 on 2021-02-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0002_auto_20210224_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='thanks_sent',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
